config/routes.rb
SharedTodoApp::Application.routes.draw do
  
  get "todos/index"
  
  match "todos/add" => "todos#add", :via => :post
  
  match "todos/delete" => "todos#delete", :as => :delete
  

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  attr_accessible :todo_item
  validates :todo_item, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  
  def index
    @todo_items = Todo.all
  end
  
  def add
    todo = Todo.create(:todo_item => params[:todo_text])
    unless todo.valid?
      flash[:error] = todo.errors.full_messages.join("<br>").html_safe
    end
    redirect_to :action => 'index'
  end
  
  def delete
    @todo_last = Todo.last
    @todo_last.delete
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SharedTodoApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/delete.html.erb
<p>Todo successfully deleted</p>
<a href="/todos/index">Back</a>

app/views/todos/index.html.erb
<title>Shared Todo App </title>
<div class="container">
  <div class="row">
    <div class="span4">
      <h1>Shared Todo App</h1>
      <hr>
      <p>All your todos here</p>
      <%= form_tag("/todos/add", :method=>"post") do %>
        <%= text_field_tag(:todo_text) %>
        <%= submit_tag("Add todo", :class=>"btn") %>
      <% end %>
      
      <% if flash[:error] %>
       <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert" >×</button>
          <strong><%= flash[:error] %></strong>
          </div>
      <% end %>
      
      <div class="well">
        <% @todo_items.each do |t| %>
         <li> <%= t.todo_item %> </li>
        <% end %>

        <%= link_to "Delete last todo", delete_path %>
        
      </div> <!-- well -->
    </div> <!-- span4 -->
  </div> <!-- row -->
</div> <!-- container -->